### ISSUE TITLE
Gripper effort is not properly handled.

### ISSUE THREAD

**Issue by mikeferguson** [moveit/moveit_plugins#2]

**Comment by isucan** [comment]
As soon as this gets merged:
https://github.com/ros/common_msgs/pull/13

We can do things right

**Comment by mikeferguson** [comment]
@isucan, I'm going to steal this one back, I plan to have it tested end-to-end on our robot by end of the week.

**Comment by isucan** [comment]
Perfect! :) Thanks!

**Comment by mikeferguson** [comment]
Fixed by #6
